apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: image-arch-webhook
  namespace: {{ .Values.namespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: image-arch-webhook
