apiVersion: v1
kind: Service
metadata:
  name: image-arch-webhook
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: image-arch-webhook
spec:
  ports:
  - port: 443
    targetPort: {{ .Values.webhook.port }}
    protocol: TCP
    name: https
  selector:
    app.kubernetes.io/name: image-arch-webhook
